### ISSUE TITLE
Argument #1 ($apiKey) must be of type string

### ISSUE THREAD

**Issue by mattglover11** [aglavas/laravelGPT#1]
Php 8.2 - getting this error running composer install

> @php artisan package:discover --ansi

   TypeError 

  Probots\Pinecone\Client::__construct(): Argument #1 ($apiKey) must be of type string, null given, called in /Users/matt/projects/clients/dohq-app/laravelgpt/app/Providers/AppServiceProvider.php on line 19

  at vendor/probots-io/pinecone-php/src/Client.php:22
     18▕     /**
     19▕      * @param string $apiKey
     20▕      * @param string $environment
     21▕      */
  ➜  22▕     public function __construct(
     23▕         public string $apiKey,
     24▕         public string $environment,
     25▕     )
     26▕     {

  1   app/Providers/AppServiceProvider.php:19
      Probots\Pinecone\Client::__construct()
      +18 vendor frames 

  20  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by aglavas** [comment]
@mattglover11 
Ah, that is leftover from the time there was only PineCone vector DB enabled in project.
Now it supports PineCone flow and PostgresVector flow.
It would need a nice refactor to a VectorDb class with PineCone and Postgres drivers, or something similar. That will come when I have enough time to clean it up. :D

Until then, this will suffice: [https://github.com/aglavas/laravelGPT/commit/85e73cfae7999e0323f0983a9cdb7b45c7876ace](https://github.com/aglavas/laravelGPT/commit/85e73cfae7999e0323f0983a9cdb7b45c7876ace)

Should be fine now, after you pull changes. Let me know, if it did help.
